### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-plc

### ISSUE THREAD

**Issue by Feilner** [Feilner/homebridge-plc#40]
After updating of the homebridge docker container (https://github.com/oznu/docker-homebridge) the homebridge-plc is not functional any more.

With following error message:
```
[6/29/2022, 10:30:04 AM] ====================
[6/29/2022, 10:30:04 AM] ERROR LOADING PLUGIN homebridge-plc:
[6/29/2022, 10:30:04 AM] Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/homebridge/node_modules/homebridge-plc/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plc/node_modules/node-snap7/lib/node-snap7.js:8:45)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
[6/29/2022, 10:30:04 AM] ====================
```

**Comment by Feilner** [comment]
The problem can be solved easily be deinstalling an installing the homebridge-plc plugin using the GUI.
